version: "3.9"

services:
  db:
    image: postgres:16
    container_name: tft-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres #Default username
      POSTGRES_PASSWORD: postgres #Default password
      POSTGRES_DB: tft
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: